on:
  push:
    branches: [main]
    paths: publiccode-validator-api.oas.yaml
  pull_request:
    branches: [main]
    paths: publiccode-validator-api.oas.yaml

permissions:
  checks: write

jobs:
  spectral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: curl --fail -L https://github.com/italia/api-oas-checker-rules/releases/download/1.1/spectral-full.yml > .spectral.yml

      # Get additional module required by spectral-full
      - run: mkdir functions
      - run: curl --fail -L https://raw.githubusercontent.com/italia/api-oas-checker/f6f4e6e360b2ce9816dcca29396571dda1c6027d/security/functions/checkSecurity.js > functions/checkSecurity.js

      - uses: stoplightio/spectral-action@v0.8.13
